name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  milliseconds:
    description: 'How long this test should pretend to do work'
    default: 1000
runs:
  using: 'node12'
  main: 'dist/index.js'
